### ISSUE TITLE
Crystal Aura Ghost Crystals[BUG]

### ISSUE THREAD

**Issue by Fex47** [pyroclient/pyro#245]
**Describe the bug**
Crystal Aura places ghost crystals (client side only)

**To Reproduce**
just turn on Crystal aura
**Expected behavior**
i expect the crystal aura not to show me fake crystals.

**Comment by MrHakan** [comment]
lol 👻👻👻

**Comment by ghost** [comment]
Personally I think ghost crystals are caused by a slow reaction of the client, I’ve seen a few clips and mostly the ghost crystals start happening when your target starts running around. I think the client misplaces the crystal when the target isn’t at correct circumstances but since pyro is so fast it places and destroys it as if it was a real crystal client sided?. I am not 100% sure as I have never had an issue of this sort and I have never done much code. Perhaps try seeing if the ghost crystals happen when the target is 100% still and meets your ca setting requirements?

**Comment by GiantNuker** [comment]
There are no ghost crystals why do people still believe the propaganda...

The only thing that could qualify is crystals serverside but not clientside. this would cause something that looks like air but isnt, and you have to destroy with a bow or another crystal
